# Generated by Django 5.0.2 on 2024-04-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_lesson_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='training.course', verbose_name='Курс'),
        ),
    ]
